baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs = false
title = "Dapr学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
# General information
    author = "敖小剑"
    keywords = "Dapr,学习笔记,敖小剑"
    description = "Dapr学习笔记。"
    copyright = "版权所有，转载请注明出处"
    
    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/skyao/learning-dapr"
    
    version = ""
    logo = "images/logo.png"
    favicon = ""
    
    permalink = "#"
    
    # reward button, comment this to disable it
    reward = true
    
    # Custom assets
    custom_css = []
    custom_js  = []
    
    # Syntax highlighting theme
    highlight_css  = ""
    
    [params.palette]
    	primary = "red"
    	accent  = "teal"
    
    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"

[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "Quickstart"
	identifier = "introduction-quickstart"
	parent = "introduction"
	url    = "/introduction/quickstart/"
	weight = 110

[[menu.main]]
	name   = "概况"
	identifier = "introduction-overview"
	url    = "/introduction/overview/"
	parent = "introduction"
	weight = 130

[[menu.main]]
	name   = "官方文档"
	identifier = "document"
	url    = "/document/"
	weight = 200

[[menu.main]]
	name   = "用户文档"
	identifier = "document-user"
	url    = "/document/user/"
	parent = "document"
	weight = 210

[[menu.main]]
	name   = "参考文档"
	identifier = "document-reference"
	url    = "/document/reference/"
	parent = "document"
	weight = 230

[[menu.main]]
	name   = "服务调用"
	identifier = "service-invoke"
	url    = "/service-invoke/"
	weight = 500

[[menu.main]]
	name   = "服务调用的文档"
	identifier = "service-invoke-docs"
	url    = "/service-invoke/docs/"
	parent = "service-invoke"
	weight = 510

[[menu.main]]
	name   = "服务调用的源码"
	identifier = "service-invoke-sources"
	url    = "/service-invoke/sources/"
	parent = "service-invoke"
	weight = 530

[[menu.main]]
	name   = "发布订阅消息"
	identifier = "pub-sub"
	url    = "/pub-sub/"
	weight = 600

[[menu.main]]
	name   = "资源绑定"
	identifier = "resource-binding"
	url    = "/resource-binding/"
	weight = 700

[[menu.main]]
	name   = "状态管理"
	identifier = "state-management"
	url    = "/state-management/"
	weight = 800

[[menu.main]]
	name   = "分布式追踪"
	identifier = "distributed-tracing"
	url    = "/distributed-tracing/"
	weight = 900

[[menu.main]]
	name   = "安全"
	identifier = "secrets"
	url    = "/secrets/"
	weight = 1000

[[menu.main]]
	name   = "Actors"
	identifier = "actors"
	url    = "/actors/"
	weight = 1100

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


